### ISSUE TITLE
working on adding a subpage for OPEN HARDWARE

### ISSUE THREAD

**Issue by mildrette** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#104]
I am already working on adding sub page to open hardware so that when the link is click it takes you to a sub page.

**Comment by BatoolMM** [comment]
Thank you @mildrette for your work, there's an open PR #36 - We'll add more tasks today!

Looking forward to your contributions!

**Comment by BatoolMM** [comment]
I will close this for now but feel free to repent it later!
