### ISSUE TITLE
Refractor code to improve the UI of the site in mobile view

### ISSUE THREAD

**Issue by oEbuka** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#106]
Refractor code to improve the UI of the site in mobile view i.e. Responsiveness

#### Actual behaviour

- [ ] *UNESCO icon too large(mobile view)*
- [ ] *margin of the Open science practices points, too small for mobile view*
- [ ] *funders section*
- [ ] *OSCSA icon too large*

I will like to handle these @BatoolMM 

![outreachy5](https://user-images.githubusercontent.com/94439139/194970679-e801a631-f89b-4da6-b6be-3ef697e6bcd4.png)
![outreachy2](https://user-images.githubusercontent.com/94439139/194970668-fb2732d0-d266-4796-9fab-af6780c0191f.png)
![outreachy3](https://user-images.githubusercontent.com/94439139/194970671-859edb09-6b8a-4b99-9960-37f794ea4b63.png)
![outreachy4](https://user-images.githubusercontent.com/94439139/194970678-1e0720f3-b1a9-4ee1-bc0d-83f6fa08ed0e.png)

**Comment by iLynette** [comment]
Hi @oEbuka can I be assigned to this one?

**Comment by BatoolMM** [comment]
Hi @oEbuka and @iLynette , thank you for your interest in improving the website!

Some of these issues are duplicates in issues #18, #19, #20, #28. Feel free to open a new issue while removing the duplicate and have a clear title and description similar using our issue template!
