### ISSUE TITLE
the funders image

### ISSUE THREAD

**Issue by Teslimsama** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#110]
the images on the funders section

**Comment by BatoolMM** [comment]
Hi @Teslimsama, please use the issue template when you submit a new issue. There's no description about the issue and what you are trying to fix. Also, there are multiple issue working on images on the funders section!

**Comment by BatoolMM** [comment]
Issues with responsiveness are mentioned in issue  #18, #19, #20, #28. Feel free to open a new issue while removing the duplicate and have a clear title and description similar using our issue template!
