### ISSUE TITLE
[11-10-2022]: Add subpage for open license

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#114]
#### Description
Subpage on brief explanation on what Open license entails

#### Expected behaviour

- [ ] *Clicking the open license pane on the home page should direct to another page showing a brief on what Open license is*

### What needs to be done?

- [ ] *Add brief summary about what open license is*
- [ ] *Add image illustration explaining more on open license*
- [ ] *Reference links to read or learn more on open license*

### Who want to work on this issue?
I am currently working on this issue

**Comment by BatoolMM** [comment]
Thank you @RealRichi3 - This is one of the best-outlined issues opened so far with a clear title and description. 

However, it was addressed in PR #62 - We will add new tasks today which you can work on it!

I will close this for now, but feel free to open it later!

**Comment by RealRichi3** [comment]
Alright @BatoolMM, thanks for your review

**Comment by RealRichi3** [comment]
Already made a PR though, but it's alright, thanks
