### ISSUE TITLE
Dead website link on README file

### ISSUE THREAD

**Issue by Jolah1** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#132]
Dead website Link on README file

###Description
Link to the website on README file is an old and broken link deployed with Netlify.

#### Expected behaviour
Link should open OSCSA website 

#### Actual behaviour
Showing error 404

### How to reproduce
 steps that a user would take to experience this bug.
1. Go to 'README.md'
2. Click on 'here' link
3. See error 404 

- OS:
* Windows 10

![Screenshot (112)](https://user-images.githubusercontent.com/99138852/195347004-75cbcc08-c309-4fda-846a-1f0a5a12a02e.png)

![photo_2022-10-12_15-36-35](https://user-images.githubusercontent.com/99138852/195373945-8ae6a3f6-8a9f-407b-b105-c15ea8997a78.jpg)
Currently working on it.

**Comment by mildrette** [comment]
please can I be assigned to this? please
