### ISSUE TITLE
Punctuation error on the landing page (footer section)

### ISSUE THREAD

**Issue by Jolah1** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#140]
#### Which task do you want to work on? 
Punctuation error on the landing page (Footer section)

#### Expected behaviour
"completing one minute survey!"

#### Actual behaviour
"completing one minute survey. !"

### What needs to be done?
Remove the full stop and leave only the exclamation mark.

### Who want to work on this issue?
Jolade (Outreachy Applicant)

![photo_2022-10-12_15-36-44](https://user-images.githubusercontent.com/99138852/195401583-0fc06bb7-379a-42fe-834d-fac3ec1f030e.jpg)
Currently working on it @BatoolMM

**Comment by Jolah1** [comment]
Issue fixed @BatoolMM , awaiting your review
Thank you.

**Comment by GuddyTech** [comment]
@Jolah1 Can I also join you in this task?

**Comment by Jolah1** [comment]
> @Jolah1 Can I also join you in this task?

@GuddyTech i would love to but the issue has already been fixed in #141 

Thank You.
