### ISSUE TITLE
[10/13/2022]:  ISSUE - would like to improve the web accessibility of the site

### ISSUE THREAD

**Issue by jesutobi** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#157]
@BatoolMM @alswajiab would like to improve the web accesibility of OSCSA website, this would help people with disability to use the platform with ease

i would be working on adding tooltip  to various call to actions or buttons in the site , this would help web assitive technologies e.g screen reader

i would also be adding short descriptions to alt attributes in all image tags  thats found in the html code

lastly : according to WAI(web accessibility initiative) using placeholders only in a form doesnt do justice to users of a certain form of disablity...so to improve this i would be adding labels to the forms

**Comment by jesutobi** [comment]
i wont be doing the second one "adding description to alt attribute" because another contributor has worked on it

**Comment by jesutobi** [comment]
@BlueDragn i am also an outreachy applicant ,but here is what is going to happen, we can split it since its two issues i discovered, so you can also have something to work on....i would take the last issue i stated i.e adding labels then you can take the other one i.e adding tooltip...thats fair i guess

**Comment by BlueDragn** [comment]
@jesutobi ofcourse, No issue.
