### ISSUE TITLE
[17/10/2022]: Fixed missing hamburger menu

### ISSUE THREAD

**Issue by Tammy-Ajoko** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#183]
#### Which task do you want to work on? 

- [ ] *Task 1*
- [ ] *Task 2*
- [ ] *Task 3*
- [ ] *Task 4*
- [ ] *Task 5*
- [ ] *Task 6*
- [x] *Unlisted Task*

#### Expected behaviour

- *A hamburger menu on Arabic mobile view.*
- *A drop-down menu on mobile view in Arabic on the main website.*
- *Translate back to English.*

#### Actual behaviour

- *No hamburger menu icon.*
-  *Can't translate to English once in Arabic.*

### What needs to be done?

- *Add missing hamburger icon in ar-index.html*

### Who want to work on this issue?
I would like to work on this

**Comment by Tammy-Ajoko** [comment]
@BatoolMM @alswajiab please could you review

**Comment by BatoolMM** [comment]
Thank you @Tammy-Ajoko, this is fantastic, we'll review it soon!

**Comment by Cadeau1** [comment]
Good day. I am an outreachy applicant, and I would like to work on this issue.

**Comment by Cadeau1** [comment]
@BatoolMM @alswajiab  Please can I work on this issue?

**Comment by Tammy-Ajoko** [comment]
@Cadeau1 I'm already working on it

**Comment by Cadeau1** [comment]
> @Cadeau1 I'm already working on it

Okay
