### ISSUE TITLE
[18/10/2022]Task3.2 : Added Event cards

### ISSUE THREAD

**Issue by sandygudie** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#186]
### Problem Statement: Tasks 3
We need to add an events subpage where we can link our events in [Zenodo](https://zenodo.org/communities/1231231664/?page=1&size=20).
 1. Add this to the nav bar.
 2. Add three cards with each event, title, name of the speaker, and language.
 3. Each card should direct you to a subpage with a description of the event, speaker, language and a link to the slides from Zenodo.
 
###  Which task do you want to work on? 
Task 3.2: Add three cards with each event, title, name of the speaker, and language.

#### Expected behavior
- [ ] *The OSCSA event should be listed on the homepage.*

### Who want to work on this issue?
@sandygudie

**Comment by ChinatuL** [comment]
Hello @sandygudie. My name is Lucia, one of the outreachy interns and I am interested in working on this task.

**Comment by BatoolMM** [comment]
@all-contributors please add @sandygudie to infra
