### ISSUE TITLE
26/10/22  There is a typo error on the OPEN SCIENCE page

### ISSUE THREAD

**Issue by GuddyTech** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#215]
#### Correcting the typo error on the OPEN SOURCE page
![1](https://user-images.githubusercontent.com/112786412/198034800-dc7f8f44-563c-49ce-9439-bc48dd8117c6.jpg)
![2](https://user-images.githubusercontent.com/112786412/198034854-4975a19e-2cbb-4a56-b54e-c05f5bdad2ea.jpg)
]](https://osc-ksa.com/)

### @sandygudie @alswajiab @BatoolMM I want to take up this task to make all necessary corrections

![1](https://user-images.githubusercontent.com/112786412/198034958-e65e9489-78d5-4748-bb19-04a1cff54d1f.jpg)
![2](https://user-images.githubusercontent.com/112786412/198035007-697e85c7-5417-43e3-8ad3-3cd7f86eb915.jpg)

**Comment by GuddyTech** [comment]
Hello @BatoolMM @alswajiab @sandygudie I am an outreachy student and I would love to take up this task in order to make all necessary corrections. Thanks

**Comment by sandygudie** [comment]
@GuddyTech go ahead and solve it
