### ISSUE TITLE
Broken Social links in footer

### ISSUE THREAD

**Issue by OsujiPius** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#42]
The Social media icons link to https://osc-ksa.com/ instead of their respective social accounts @BatoolMM 
[screen-capture (4).webm](https://user-images.githubusercontent.com/94569961/194781677-6236aa91-7a9c-4f04-a63c-cb749c5af75a.webm)

**Comment by mildrette** [comment]
I have fix those an open a PR. i added a hover effect to the icons so one will know they are clickable

**Comment by BatoolMM** [comment]
Thank you @OsujiPius, this was fixed in PR #56.
