### ISSUE TITLE
Complete Redesign of the Footer component

### ISSUE THREAD

**Issue by okerekechinweotito** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#47]
Total Redesign of the footer component

**Comment by BatoolMM** [comment]
Please add more details to your issue and use the issue template that we have. A similar issue is posted in #45

**Comment by okerekechinweotito** [comment]
@BatoolMM  I would like to close this issue as I will not be working on it. It is a duplicate

**Comment by BatoolMM** [comment]
You can close any duplicate issue @okerekechinweotito by clicking on "close with comment". Please close any duplicate issue you have!
