### ISSUE TITLE
Refactor the UI and add more testimonials on UNESCO Recommendation section

### ISSUE THREAD

**Issue by okerekechinweotito** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#54]
Refactor code and add more content and testimonials to the UNESCO Recommendation  on Open science Section

**Comment by BatoolMM** [comment]
Thank you for your work but I am not sure what you are trying to do, can you add more description in the issue you open, please?

**Comment by BatoolMM** [comment]
Thank you for your work but I am not sure what you are trying to do, can you add more description in the issue you open, please?

**Comment by okerekechinweotito** [comment]
@BatoolMM   This issue is already been addressed by someone else in #60 
I will no longer work on this issue. Pls mark as duplicate ignore this issue

**Comment by BatoolMM** [comment]
Thank you @okerekechinweotito!
