### ISSUE TITLE
Fix broken social link on footer

### ISSUE THREAD

**Issue by sandygudie** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#61]
The social media icons on the footer of the official OSCSA website have broken links.

![image](https://user-images.githubusercontent.com/54219127/194830917-baf68850-c6f7-4167-a6a2-8e465dd555a2.png)

**Comment by sandygudie** [comment]
Hi @OsujiPius i worked on this earlier and created a [PR](https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA_Website/pull/56), i just created the issue to reflect the PR.

**Comment by BatoolMM** [comment]
I will close this issue now, feel free to open it later!

**Comment by BatoolMM** [comment]
Please make sure you create the issue before the PR and provide elaborate descriptions using the template for both the issue and PR!
