### ISSUE TITLE
Missing favicon image on the OSCSA website

### ISSUE THREAD

**Issue by sandygudie** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#63]
The OSCSA website has a missing favicon image. This also shows the console as an error. 
![image](https://user-images.githubusercontent.com/54219127/194759798-7b35faaa-61e9-475d-833e-ed3b9fb38476.png)

The OSCSA Logo should replace the favicon.

**Comment by Jolah1** [comment]
Hello @bebatut 
My name is Jolade, I am an Outreachy applicant, I will love to be assigned this issue
thank you.

**Comment by BatoolMM** [comment]
Hi @Jolah1, thank you for expressing interest, it seems that @sandygudie has already initiated a PR. 
@Jolah1 We have a list of tasks in issue #12 - please feel free to chose from it!

**Comment by BatoolMM** [comment]
This was fixed in #25.
