### ISSUE TITLE
Website error - internal server error

### ISSUE THREAD

**Issue by sagesharp** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#7]
Going to [https://osc-ksa.com/](https://osc-ksa.com/) currently results in an internal server error:

"Internal Server Error - Request ID: 01FXQGMZXVYWMC3SK4Y6QEH1P8"

**Comment by BatoolMM** [comment]
Thank you for reporting this! 
Interesting!  it works just fine for me, can you try this https://www.osc-ksa.com/? let me know if you get the same error!

**Comment by BatoolMM** [comment]
Glad it works!
