### ISSUE TITLE
Blog section in the Arabic version

### ISSUE THREAD

**Issue by Mublin** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#71]
Assalamu Alaikum @alswajiab @BatoolMM the website does not have a blog section in the arabic version

**Comment by BatoolMM** [comment]
The Blog use Quarto and we will open an issue to address this!

**Comment by Mublin** [comment]
> The Blog use Quarto and we will open an issue to address this!

Ok Ma @BatoolMM @alswajiab I will be waiting, please assign me to the task so we can add the blog dynamically, شكرلك
