### ISSUE TITLE
Events Subpage

### ISSUE THREAD

**Issue by OsujiPius** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#86]
This will add an events subpage where we can link our events in [Zenodo](https://zenodo.org/communities/1231231664/?page=1&size=20).

Will also three cards with each event, title, the name of the speaker, and language.
Each card should direct you to a subpage with a description of the event, speaker, language and a link to the slides from Zenodo
it will  reflected on both the Arabic and English pages.

@BatoolMM I will like to work on this

**Comment by BatoolMM** [comment]
Thank you @OsujiPius - an issue has been opened in #87
