### ISSUE TITLE
Add a drop-down for About us.

### ISSUE THREAD

**Issue by Khadeeejah** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#89]
Task 2
 In the dropdown, we want to add

Who are we?
This will direct you to the same about us page on the website
Code of Conduct
This will direct you to a new subpage with [the code of conduct](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/blob/main/CODE_OF_CONDUCT.md)
Make sure it's reflected on both the Arabic and English pages.

**Comment by Khadeeejah** [comment]
@BatoolMM can you assign this to me and also add the outreachy label.
thank you

**Comment by okerekechinweotito** [comment]
@Khadeeejah @BatoolMM   This issue has already been assigned to me

**Comment by okerekechinweotito** [comment]
.. at #83

**Comment by BatoolMM** [comment]
@Khadeeejah If you opened a duplicated issue, please close it, thank you!
