### ISSUE TITLE
Working on Task 3

### ISSUE THREAD

**Issue by ladyami** [Open-Science-Community-Saudi-Arabia/OSCSA_Website#96]
I created this issue to notify that i have started working on task 3 thank you.

**Comment by Mublin** [comment]
@ladyami i am already working on that

**Comment by ladyami** [comment]
@Mublin did you create issue about it ( have check before I started I did not see any issue about ) or @BatoolMM  assign the task to you? i was also working on the website SEO but when i notice a issue have open about it i have to drop it.

**Comment by ladyami** [comment]
@Mublin  I am sorry I just recheck I didn't see it before you can continue working on it I will drop it best of luck.

**Comment by BatoolMM** [comment]
Thank you @ladyami for your hard work and for kindly discussing this issue!

If you opened a duplicate issue, please close it!

**Comment by ladyami** [comment]
okay ma I will close it Immediately
